version: 1.0.{build}
image: Visual Studio 2019
branches:
  only:
  - master
skip_tags: true
configuration: Release
platform: x64
before_build:
- cmd: nuget restore
build:
  project: PEM2PPK.sln
  verbosity: minimal
artifacts:
- path: PEM2PPK\bin\Release
  name: pem2ppk_stable
deploy:
- provider: GitHub
  tag: PEM2PPK-v$(appveyor_build_version)
  release: PEM2PPK-v$(appveyor_build_version)
